name: test

run-name: test code geometric_lib
on:
  push:
    branches:
      - main
      - develop
      - feat/tests
      - release/*
  pull_request:
    branches:
      - master
      - release/*
      - develop
      - feat/tests

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STUDENT_NAME: "Obuchova Viktoria Romanovna"
      GROUP_NUMBER: "M3116"

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: feat/tests 
          
      - name: Print Info
        run: |
          echo "Full name: ${{ env.STUDENT_NAME }}"
          echo "Group: ${{ env.GROUP_NUMBER }}"
          echo "Nickname on Github: ${{ github.actor }}"
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Check code style
        run: black --check .

      - name: Format code (optional)
        run: black .
